package EXERCICES.EX3.proxy;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "EtudiantSOAPServiceService", targetNamespace = "myservices", wsdlLocation = "http://localhost:8087/EX3/etudiantService?wsdl")
public class EtudiantSOAPServiceService
        extends Service {

    private final static URL ETUDIANTSOAPSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException ETUDIANTSOAPSERVICESERVICE_EXCEPTION;
    private final static QName ETUDIANTSOAPSERVICESERVICE_QNAME = new QName("myservices", "EtudiantSOAPServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8087/EX3/etudiantService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ETUDIANTSOAPSERVICESERVICE_WSDL_LOCATION = url;
        ETUDIANTSOAPSERVICESERVICE_EXCEPTION = e;
    }

    public EtudiantSOAPServiceService() {
        super(__getWsdlLocation(), ETUDIANTSOAPSERVICESERVICE_QNAME);
    }

    public EtudiantSOAPServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ETUDIANTSOAPSERVICESERVICE_QNAME, features);
    }

    public EtudiantSOAPServiceService(URL wsdlLocation) {
        super(wsdlLocation, ETUDIANTSOAPSERVICESERVICE_QNAME);
    }

    public EtudiantSOAPServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ETUDIANTSOAPSERVICESERVICE_QNAME, features);
    }

    public EtudiantSOAPServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EtudiantSOAPServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (ETUDIANTSOAPSERVICESERVICE_EXCEPTION != null) {
            throw ETUDIANTSOAPSERVICESERVICE_EXCEPTION;
        }
        return ETUDIANTSOAPSERVICESERVICE_WSDL_LOCATION;
    }

    /**
     * @return returns EtudiantService
     */
    @WebEndpoint(name = "etudiantServicePort")
    public EtudiantService getEtudiantServicePort() {
        return super.getPort(new QName("myservices", "etudiantServicePort"), EtudiantService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns EtudiantService
     */
    @WebEndpoint(name = "etudiantServicePort")
    public EtudiantService getEtudiantServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("myservices", "etudiantServicePort"), EtudiantService.class, features);
    }

}
