package EXERCICES.EX3.proxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "etudiantService", targetNamespace = "myservices")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface EtudiantService {


    /**
     * @param name
     * @return returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNote", targetNamespace = "myservices", className = "myservices.GetNote")
    @ResponseWrapper(localName = "getNoteResponse", targetNamespace = "myservices", className = "myservices.GetNoteResponse")
    @Action(input = "myservices/etudiantService/getNoteRequest", output = "myservices/etudiantService/getNoteResponse")
    public double getNote(
            @WebParam(name = "name", targetNamespace = "")
                    String name);

    /**
     * @return returns java.util.List<myservices.Etudiant>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEtudiants", targetNamespace = "myservices", className = "myservices.GetEtudiants")
    @ResponseWrapper(localName = "getEtudiantsResponse", targetNamespace = "myservices", className = "myservices.GetEtudiantsResponse")
    @Action(input = "myservices/etudiantService/getEtudiantsRequest", output = "myservices/etudiantService/getEtudiantsResponse")
    public List<Etudiant> getEtudiants();

    /**
     * @return returns java.util.List<myservices.Etudiant>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEtudiantsMajorants", targetNamespace = "myservices", className = "myservices.GetEtudiantsMajorants")
    @ResponseWrapper(localName = "getEtudiantsMajorantsResponse", targetNamespace = "myservices", className = "myservices.GetEtudiantsMajorantsResponse")
    @Action(input = "myservices/etudiantService/getEtudiantsMajorantsRequest", output = "myservices/etudiantService/getEtudiantsMajorantsResponse")
    public List<Etudiant> getEtudiantsMajorants();

    /**
     * @return returns java.util.List<myservices.Etudiant>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEtudiantsValidants", targetNamespace = "myservices", className = "myservices.GetEtudiantsValidants")
    @ResponseWrapper(localName = "getEtudiantsValidantsResponse", targetNamespace = "myservices", className = "myservices.GetEtudiantsValidantsResponse")
    @Action(input = "myservices/etudiantService/getEtudiantsValidantsRequest", output = "myservices/etudiantService/getEtudiantsValidantsResponse")
    public List<Etudiant> getEtudiantsValidants();

}
